#include <stdio.h>
#include "KalmanFilter.h"
#include "LQR.h"

int main() {
    // File path for the input data generated by GenerateDataC.c
    const char* inputFilePath = "system_data.txt";
    FILE* inputFile = fopen(inputFilePath, "r");
    if (!inputFile) {
        perror("Failed to open input file");
        return -1;
    }

    // Initialize Kalman Filter
    KalmanFilter kf;
    int kfStateSize = 1; // Adjust according to your system
    int kfControlSize = 1; // Adjust according to your system
    int kfMeasurementSize = 1; // Adjust according to your system
    kalman_init(&kf, kfStateSize, kfControlSize, kfMeasurementSize);
    // Set Kalman Filter matrices (A, B, H, Q, R, etc.) here

    // Initialize LQR Controller
    LQR lqr;
    int lqrStateSize = 1; // Adjust according to your system
    int lqrControlSize = 1; // Adjust according to your system
    lqr_init(&lqr, lqrStateSize, lqrControlSize);
    // Set LQR matrices (A, B, Q, R) here

    // Prepare vectors for measurement, state estimate, and control input
    gsl_vector* measurement = gsl_vector_alloc(kfMeasurementSize);
    gsl_vector* stateEstimate = gsl_vector_alloc(kfStateSize);
    gsl_vector* controlInput = gsl_vector_alloc(lqrControlSize);

    double measValue;
    while (fscanf(inputFile, "%lf", &measValue) != EOF) {
        // Update measurement vector
        gsl_vector_set(measurement, 0, measValue);

        // Process measurement through Kalman Filter
        kalman_process(&kf, NULL, measurement); // Assuming no control input for Kalman prediction

        // Use the state estimate from Kalman Filter as input to LQR controller
        gsl_vector_memcpy(stateEstimate, kf.x); // Copying state estimate from Kalman Filter
        lqr_process(&lqr, stateEstimate, controlInput); // Compute control input with LQR

        // Control input 'controlInput' is now ready to be used
        // You might want to log it, use it in a simulation, send it to a physical system, etc.
    }

    // Cleanup
    fclose(inputFile);
    gsl_vector_free(measurement);
    gsl_vector_free(stateEstimate);
    gsl_vector_free(controlInput);
    kalman_free(&kf);
    lqr_free(&lqr);

    return 0;
}
